services:
  - type: web
    name: notesapp-backend
    env: node
    plan: free
    region: oregon   # or your preferred region
    branch: main
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your DB connection string here (MongoDB Atlas for example)
      - key: MONGODB_URI
        sync: false
